### ISSUE TITLE
Przygotować aplikacje od nowa

### ISSUE THREAD

**Issue by Danon** [fuzionu/champions#4]
- Projekt ma się nazywać `Champions`
    - Czyli mają się pojawić pliki `Champions.dpr`, `Champions.exe`, etc.
 - Formularz ma mieć klasę `TChampionForm`
 - Logika na temat championów (`GetChampion(string)`, `ChampionExists(string)`, etc.) ma być w osobnymi pliku `Champion.pas`.
 - Layout ma być podobny do tego jak aplikacja wyglądała wcześniej.
 - Interfejsem pomiędzy `TChampionForm` a `Champion.pas` do danych o championach (imię, obrazek, staty) ma być `TChampion` (żadnej metody na 30 argumentów z ad,ap,ms,armor, etc.).

**Comment by fuzionu** [comment]
done
